name: Build & Test
"on":
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version: '>=1.21.1'
    - name: Set GOVERSION environment variable (Linux/macOS)
      if: runner.os != 'Windows'
      run: echo "GOVERSION=$(go version)" >> $GITHUB_ENV
    - name: Set GOVERSION environment variable (Windows)
      if: runner.os == 'Windows'
      run: echo "GOVERSION=$(go version)" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Build & Test
      run: |
        go build -v
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6
      with:
        args: release --snapshot --skip=publish --clean
    - name: Colored Output Test
      if: runner.os == 'Linux'
      shell: script -q -e -c "bash {0}"
      run: go run main.go -- main.go
